version: 2
jobs:
  build:
    working_directory: ~/Project/MobileAutomationTest
    docker:
    - image: circleci/android:api-26-alpha
    environment:
    - JVM_OPTS: -Xmx3200m
    steps:
    - checkout:
        path: ~/Project/MobileAutomationTest/
    - run:
        name: checking path of git directory
        command: pwd
    - run:
        name: Chmod permissions
        command: sudo chmod +x ./AndroidDemo/gradlew
    - run:
        name: Download Dependencies
        command: ./AndroidDemo/gradlew dependencies
    - run:
        name: Setup emulator
        command: yes | sdkmanager --licenses && sdkmanager --update;sdkmanager "platform-tools" "platforms;android-24" "emulator" "system-images;android-24;default;armeabi-v7a" 
    - run:
        name: Launch emulator
        command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
        background: true
    - run:
        name: Wait emulator
        command: |
          # wait for it to have booted
          circle-android wait-for-boot
          # unlock the emulator screen
          sleep 30
          adb shell input keyevent 82
    - run:
        name: Run Test case
        command: cd AndroidDemo && ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.mytaxi.android_demo.tests.CallDriverTest
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
