version: 2
jobs:
  build:
    working_directory: ~/Project/MobileAppAutomationTest
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms1024m -Xmx1536m -XX:MaxMetaspaceSize=1536m"
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false -DdisablePreDex'
    steps:
      - checkout
      - run:
          name: Path
          command: pwd
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./AndroidDemo/gradlew
      - run:
          name: Download Dependencies
          command: ./AndroidDemo/gradlew dependencies         
      - run:
          name: Accept all licences
          command: yes | sdkmanager --licenses || exit 0 && yes | sdkmanager --update || exit 0 
      - run:
          name: Setup emulator
          command: echo y | sdkmanager "platform-tools" "platforms;android-22" "emulator" "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on -gpu off
          background: true 
      - run:
          name: Wait emulator
          command:  |
           circle-android wait-for-boot
           sleep 30
           adb shell input keyevent 82 
      - run:
          name: Run UI Tests
          command: cd AndroidDemo && ./gradlew connectedAndroidTest
      - store_artifacts:
          path: AndroidDemo/app/build/reports
          destination: reports
