version: 2
jobs:
  build:
    working_directory: ~/Project/MobileAutomationTest
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms1024m -Xmx1536m -XX:MaxMetaspaceSize=1536m"
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false -DdisablePreDex'
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./AndroidDemo/gradlew
      - run:
          name: Download Dependencies
          command: ./AndroidDemo/gradlew dependencies         
      - run:
          name: Setup emulator
          command: sdkmanager --update && echo y | sdkmanager "platform-tools" "platforms;android-22" "emulator" "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: emulator -avd circleci-android22 -no-audio -no-window
          background: true 
      - run:
         name: Wait emulator
         command: |
           circle-android wait-for-boot
           sleep 30
           adb shell input keyevent 82     
      - run:
          name: Run UI Tests
          command: cd /AndroidDemo/gradlew connectedAndroidTest
  
workflows:
  version: 2
  workflow:
    jobs:
    - build
